spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1
        - id: merchant-service
          uri: lb://merchant-service
          predicates:
            - Path=/api/merchants/**
          filters:
            - StripPrefix=1
        - id: merchant-search-service
          uri: lb://merchant-service
          predicates:
            - Path=/api/foods/**
          filters:
            - StripPrefix=1
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix=1
        - id: consumer-service
          uri: lb://consumer-service
          predicates:
            - Path=/api/cart/**
          filters:
            - StripPrefix=1
